FROM --platform=$TARGETPLATFORM python:3.11-slim

# 시스템 패키지 설치
RUN apt-get update && apt-get install -y \
  ffmpeg \
  build-essential \
  libgl1-mesa-glx \
  libglib2.0-0 \
  libpng-dev \
  libjpeg-dev \
  curl \
  git \
  vim \
  nano \
  zsh \
  && rm -rf /var/lib/apt/lists/* \
  && sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended \
  && git clone https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k \
  && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions \
  && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# requirements.txt 복사 및 패키지 설치
COPY requirements.txt ./
RUN pip install -r requirements.txt

# zsh 설정 파일 복사
COPY ./zsh/zshrc /root/.zshrc
COPY ./zsh/p10k.zsh /root/.p10k.zsh
COPY ./.project_root ./app/.project_root

# pip 업그레이드
RUN python -m pip install -U pip setuptools wheel

# 작업 디렉토리 설정
WORKDIR /app



# 볼륨 마운트 디렉토리 준비
RUN mkdir -p /app/data /app/runs \
  && chmod 777 /app/data /app/runs

# 환경 변수 설정
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONPATH=/app