services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev # 개발용 Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./src:/app/src
      - ./runs:/app/runs
      - poetry-cache:/root/.cache/pypoetry
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    stdin_open: true
    tty: true
    command: tail -f /dev/null

  prod:
    build:
      context: .
      dockerfile: Dockerfile # 배포용 Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    volumes:
      - ./data:/app/data
      - ./runs:/app/runs

volumes:
  poetry-cache:
